configured_endpoints: 105
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/nvidia-ishandhanani%2Fnvidia-gpu-cloud-7f0aa99cc03e38b5c0f449943aaaec43861131521f12ba8724b73af96940a6d8.yml
